org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.3.11
forge_version_range=[40.3.11,41)
loader_version_range=[40,41)
mapping_channel=official
mapping_version=1.18.2

mod_id=vhaccelerator
mod_name=VH Accelerator
mod_artifact_name=VH-Accelerator
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.hoyin1600p.vhaccelerator
mod_authors=hoyin1600p
mod_description=Forge 1.18.2 launch, login, and transfer optimizations for Vault Hunters.
